server:
  port: 8080
management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
springdoc:
  packagesToScan: uk.gov.hmcts.juror
  writer-with-order-by-keys: true
spring:
  config:
    import: "optional:configtree:/mnt/secrets/juror/"
  application:
    name: HMCTS API Job Executor
azure:
  application-insights:
    instrumentation-key: ${juror.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
logging:
  level:
    uk.gov.hmcts.juror: info
uk:
  gov:
    hmcts:
      juror:
        security:
          use-database: false
          token-validity: 18000
          secret: ${SECRET:WW91clZlcnlWZXJ5VmVyeVNlY3JldEtleVRoYXRJc1NvU2VjcmV0SURvbnRFdmVuS25vd0l0}
        job:
          execution:
            remote:
              scheduler-service-update-status-url: /job/{job-key}/task/{task-id}/status
              scheduler-service-get-latest-status-url: /job/{job-key}/status
              scheduler-service-get-status-url: /job/{job-key}/task/{task-id}
              scheduler-service:
                security:
                  claims:
                    permissions:
                      - task::status::update
                      - task::view
                      - job::view::status
                  issuer: api-job-execution-service
                  secret: ${SCHEDULER_SERVICE_SECRET:WW91clZlcnlWZXJ5VmVyeVNlY3JldEtleVRoYXRJc1NvU2VjcmV0SURvbnRFdmVuS25vd0l0}
                  subject: ${SCHEDULER_SERVICE_SUBJECT:external-api@juror-scheduler-api.hmcts.net}
                  token-validity: 300000
                  authentication-prefix: "Bearer "
                host: ${SCHEDULER_SERVICE_HOST:localhost}
                port: ${SCHEDULER_SERVICE_PORT:8083}
                scheme: https
              police-national-computer-check-service:
                security:
                  claims:
                    permissions:
                      - pnc::check::bulk
                      - pnc::check::single
                  issuer: api-job-execution-service
                  subject: ${POLICE_NATIONAL_COMPUTER_CHECK_SERVICE_SUBJECT:api-job-execution-service}
                  secret: ${POLICE_NATIONAL_COMPUTER_CHECK_SERVICE_SECRET:WW91clZlcnlWZXJ5VmVyeVNlY3JldEtleVRoYXRJc1NvU2VjcmV0SURvbnRFdmVuS25vd0l0}
                  token-validity: 300000
                  authentication-prefix: "Bearer "
                host: ${POLICE_NATIONAL_COMPUTER_CHECK_SERVICE_HOST:localhost}
                port: ${POLICE_NATIONAL_COMPUTER_CHECK_SERVICE_PORT:8084}
                url: /jurors/check/bulk
                scheme: https
              juror-service:
                scheme: https
                host: ${JUROR_SERVICE_HOST:localhost}
                port: ${JUROR_SERVICE_PORT:8084}
                url: /api/v1/moj/juror-record/pnc/{jurorNumber}
                security:
                  id: JDCRON001
                  issuer: pnc-check-service
                  token-validity: 160000
                  subject: pnc-check-service
                  secret: ${JUROR_SERVICE_SECRET:WW91clZlcnlWZXJ5VmVyeVNlY3JldEtleVRoYXRJc1NvU2VjcmV0SURvbnRFdmVuS25vd0l0}
                  claims:
                    login: AUTO
                    userType: SYSTEM
                    userLevel: "1"
                    daysToExpire: 6
                    passwordWarning: true
                    staff:
                      name: AUTO
                      rank: -1
                      active: 1
                      courts: [ ]
jobs:
  pool-transfer:
    database:
      schema: juror_mod
  print:
    ftp-directory: /tmp/ftp_print
    sftp:
      host: ${BAIS_HOST:localhost}
      port: ${BAIS_PORT:2222}
      user: ${BAIS_XEROX_USER:userName101}
      azure-deployment: true
      private-key: /mnt/secrets/juror/bais-xerox-key
      session-wait-timeout: 10000
      pool-size: 10
      allow-unknown-keys: true
      remote-directory: /
    print-file-row-limit: 2000
  payment:
    ftp-directory: /tmp/ftp_payment
    sftp:
      host: ${BAIS_HOST:localhost}
      port: ${BAIS_PORT:2222}
      user: ${BAIS_SSCL_USER:userName101}
      azure-deployment: true
      private-key: /mnt/secrets/juror/bais-sscl-key
      session-wait-timeout: 10000
      pool-size: 10
      allow-unknown-keys: true
      remote-directory: /
  housekeeping:
    juror-digital:
      retention-threshold: 1
      database:
        schema: HK
    standard:
      max-log-file-age-in-days: 10
      log-file-directory: /Users/benedwards/Desktop/JurorTest/logs
      max-runtime: 240
      read-only: false
      owner-restrict: false
      database:
        schema: HK
  stats:
    performance:
      database:
        schema: juror_dashboard
      deferrals-no-months: 11
      excusals-no-months: 11
      response-times-and-non-respond-no-months: 6
      thirdparty-online-no-months: 6
      welsh-online-responses-no-months: 6
  checks:
    dashboard-morning-checks:
      checks-file: /filestore/HOME/jurorpl/checks.txt
      archive-folder: /filestore/HOME/jurorpl/bin/morning_checks/archive
      juror-pl-tmp-directory: /filestore/HOME/jurorpl/tmp
      expected-job-config-location: /Users/benedwards/Desktop/JurorTest/morningChecksConfig.json
    pnc:
      batch:
        batch-size: 500
  dashboard:
    ams:
      sftp:
        host: "localhost"
        port: 2222
        password: password404
        user: userName101
        azure-deployment: false
        remote-directory: print
        private-key: /Users/benedwards/.ssh/id_ecdsa
        session-wait-timeout: 10000
        pool-size: 10
        allow-unknown-keys: true
      pnc-certificate-location: tbc
      pnc-certificate-password: tbc
      pnc-certificate-alias: tbc
defaults:
  database:
    username: ${DB_USERNAME:system}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:}
    schema: "juror_mod"

