package uk.gov.hmcts.juror.job.execution.jobs.checks.pnc.batch;

import lombok.Getter;

@Getter
public enum PoliceCheck {
    NOT_CHECKED,
    INSUFFICIENT_INFORMATION,
    IN_PROGRESS,
    ELIGIBLE,
    INELIGIBLE,

    ERROR_RETRY_NAME_HAS_NUMERICS,
    ERROR_RETRY_CONNECTION_ERROR,
    ERROR_RETRY_OTHER_ERROR_CODE,
    ERROR_RETRY_NO_ERROR_REASON,
    ERROR_RETRY_UNEXPECTED_EXCEPTION,
    ERROR_RETRY_FAILED_TO_UPDATE_BACKEND,
    UNCHECKED_MAX_RETRIES_EXCEEDED
}
